unique_ids:
  assets:
    standard-page.html: JUPV3SPC2JQR5ANHCNWLZRI2IP4GRXZO
    theme.css: Y5VNBTFAXFZFAN76MRIK5JOZQ5XLOMCD
  forms:
    Form1: ESQNA6K5TATAW24LBXDMUY25SPVOYV2K
  modules: {}
  scripts: {}
  server_modules: {}
